%% EMG Data Visualization Script 
% December 2022 
% Lab rotation - Cognitive Neuromodulation Lab 

% The existing code served as a template to work from 

%% Read in data 
% workDir = fullfile('~','Documents','Publication','M1TUS_2','rawData');      % CUSTOMIZE: write location of the data on your own computer 
% cd(workDir);                                                                % Navigate to location of data 
workDir='C:\Users\user\Documents\Courses\Lab Rotation\Verhagen\EMG Analysis\rawData';
filePattern = 'P*.mat';                                                     % Data file pattern: always begins with P and ends with .mat                
fileList = dir([workDir filesep filePattern]);                              % Get a list of all data files with that pattern in the relevant directory
dataFiles = {fileList.name};                                                % Get a list with only the names of the data files (no extra info)
N = length(dataFiles);                                                      % N = the amount of data files = the amount of participants 
clear filePattern workDir                                                   % Declutter workspace


%% Manual exclusion of poor quality data 
axeTrial = cell(1,N);     
axeTrial{1} = [211,212];
axeTrial{2} =[72,132,161]; 
axeTrial{4} = [72,131,132,133,134,161];
axeTrial{5} = [50,81,117,161]; 
axeTrial{6} = [28,60,81,91,157,228]; 
axeTrial{7} = 81; 
axeTrial{8} = [71,81,89,162,163,164,181,229,241]; 
axeTrial{9} = 161; 
axeTrial{10} = [81,161]; 
axeTrial{11} = [60:80,81];
axeTrial{12} = [81,161,239,240]; 
axeTrial{13} = [81,101,161,188]; 
axeTrial{14} = [61,81,87,95,116,121,124,142,181,201]; 
axeTrial{15} = [81,113,154,161,248]; 
axeTrial{16} = [81,122,131,161]; 
axeTrial{17} =[16,81,162,176,210]; 
axeTrial{18} =[81,130,161]; 
axeTrial{19} =[81,161,162,190]; 
axeTrial{21} = [81,145,161]; 
axeTrial{22} =[81,161]; 
axeTrial{23} =[81,91,161]; 
axeTrial{24} = [41,61,81,97,101,161,201,221]; 
axeTrial{25} = [81,141,148,161,178,241,242,250];
axeTrial{26} = [49,69,81,84,94,98,113,117,161,171,203,213]; 
axeTrial{27} = [81,146,161]; 
axeTrial{28} = [81,161,187,188,189]; 
axeTrial{29} = [81,161]; 
axeTrial{30} = [11,81,161]; 

%% Process data 
winStart = 15010;                                                           % INPUT: indicate when MEP time window should start                                   
winLength =  200;                                                           % INPUT: indicate the length of the MEP calculation time window                              

for n = 1:N                                                                 % For each individual participant 
    data = load(dataFiles{n});                                              % Load in the data 
    name=fieldnames(data);                                                  % Find the data name generated by Signal 
    name=name{1};                                                           % Isolate data name 
    y = data.(name).values;                                                 % Create variable with EMG data values 
    
    % The variable y now holds the EMG data for one participant 
    % There are 25000 data points per trial 
    % These data points are muscular activity in mV 
    % There are 250 trials with 25000 data points EACH TRIAL (Each data
    % point is a time-> x-axis)
    
    y = squeeze(y);                                                         % Reduce to 2 dimensions (only 1 electrode is measured) 
    y = y(winStart:(winStart+winLength-1),:);                               % Crop EMG data to MEP calculation time window. From 25000 data points we get 200 data points per trial

    plot(y);                                                                % Have a quick look at the data for this participant
    %pause(2); 
    close; 
    
    % Now we put the EMG data into cells per trial so that it can fit
    % nicely in a table. Make a 200x250 array to a row cell array, that
    % contains column vectors. This is done just to look more beautiful
    y = num2cell(y,1); 
   
    % Now we want to get the other information that we need: 
    % 1) Participant code 
    ParticipantCode(1:size(y,2)) = {name(1:3)};                             % Create array for participant code (PXX) 
    % 2) Trial number 
    Trial = [data.(name).frameinfo.number]';
    % 3) What condition for each trial 
    Condition = {data.(name).frameinfo.label};
    
        % Baseline: only TMS was administered 
        
        % TUS: ultrasonic stimulation was applied to the primary motor
        % cortex (here, we would expect to see a reduction in MEP amplitude
        % because of inhibition by TUS)
        
        % AC: ultrasonic stimulation was applied to a control region (here,
        % we would not expect to see a reduction in MEP amplitude, because
        % TUS is administered to an irrelevant brain region. (sneak peak,
        % we still do see a reduction of MEP amplitude though)
        
        % 10W: ultrasonic stimulation was applied at 10 W/cm^2 
        
        % 30W: ultrasonic stimulation was applied at 30 W/cm^2 
        
        % NM: ultrasonic stimulation was applied without an auditory
        % masking stimulus (a sound that plays at the same time as ultrasonic stimulation, to
        % cover any audible differences between TUS and AC. 
        
        % M: ultrasonic stimulation was applied with an auditory masking
        % stimulus. 

        
        % Pull all the data for this participant together in a table 
        concatData = table(ParticipantCode',Trial,Condition',y');
        concatData.Properties.VariableNames = {'ParticipantCode','Trial', ... 
            'Condition','EMG'};
        
        % Remove the rows that have been manually detected as poor quality
        % for this participant
        concatData(axeTrial{n},:) = []; 
        
        
        if n==1
            dataset = concatData;                                              % If on first participant, then define dataset as the subject-level dataset
        else
            dataset = cat(1,dataset,concatData);                               % If after first participant, append the subject-level dataset on top of the previous subjects
        end 
end 

%% Visualization 
% The rest is up to you! Here is a little bit of structure to guide you
% thorugh what might be interesting to look at: 
% 1) Does TUS_10W_NM reduce from Baseline? 

MEP1_total=0;
MEP2_total=0;
m=0;
i=0;
for n=1:248
    if isequal(dataset.Condition{n,1} ,'Baseline (state 1)')
        MEP1=max(dataset.EMG{n,1})-min(dataset.EMG{n,1});
        MEP1_total=MEP1+MEP1_total;
        m=m+1;
    elseif isequal(dataset.Condition{n,1} ,'TUS_10W_NM (state 7)')
        MEP2=max(dataset.EMG{n,1})-min(dataset.EMG{n,1});
        MEP2_total=MEP2+MEP2_total;
        i=i+1;
    end 
    
end 
MEP_Baseline_Average=MEP1_total/m;
MEP_TUS10W_NM_Average=MEP2_total/i;

if MEP_Baseline_Average>MEP_TUS10W_NM_Average
    disp('TUS_10W_NM reduce from Baseline')
else
    disp('TUS_10W_NM increases from Baseline')
end 

plot(y{1,1})
% 2) Does AC_10W_NM reduce from Baseline? 
% 3) Does Sham reduce from Baseline? 
% 4) Do TUS, AC, and Sham differ from one another? 
% 5) Is there a difference between TUS_10W and TUS_30W, and does masking
% matter there? 
% 6) Really anything you want to have a look at 

% Here's some background 
% TUS has been shown to reduce MEP amplitude as compared to baseline in the
% past, but we think this might just be because of sound. To control for
% the sound caused by TUS, we apply stimulation to a control region (which
% should have no effect - AC) and we also administer just a sound alone
% (sham). If the effect is caused by sound, we would expect these
% conditions to also have lower MEPs than baseline. 
% Even if it is caused by sound, it is possible that there is still an
% effect of TUS. To test this, we would directly compare TUS with the AC
% and sham conditions. 
% On top of that, we also looked at some stimulation parameters. First, we
% looked at stimulation intensity (10W/30W), where we would expect higher
% intensities to have a greater effect. 
% Additionally, it is possible that the sound caused by stimulation sounds
% different for on-target (TUS) and active control (AC). To account for possible
% audible differences, we look at stimulation both with an auditory masking
% stimulus (_M) and without (_NM). 



